<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<Nullable>enable</Nullable>
		<Version>$(ZenitiumDnsVersion)</Version>
		<ServerGarbageCollection>true</ServerGarbageCollection>
		<ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ZenitiumDns.Core\ZenitiumDns.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="install.sh;uninstall.sh;start.sh;systemd.service;openrc.service">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
