<Project>

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<Company>ZenitiumDNS</Company>
		<Product>ZenitiumDNS</Product>
		<Authors>ZenitiumDNS contributors, Shreyas Zare</Authors>
		<ZenitiumDnsVersion>15.5.1</ZenitiumDnsVersion>
		<ZenitiumDnsRevision>5</ZenitiumDnsRevision>
		<TechnitiumVersion>15.5.1</TechnitiumVersion>
	</PropertyGroup>

</Project>
