#!/bin/sh
set -e

serviceName="zenitiumdns"

case "$1" in
    remove|deconfigure)
        if [ -d /run/systemd/system ]
        then
            systemctl stop "$serviceName.service" >/dev/null 2>&1 || true
            systemctl disable "$serviceName.service" >/dev/null 2>&1 || true
        fi
        ;;

    upgrade)
        if [ -d /run/systemd/system ]
        then
            systemctl stop "$serviceName.service" >/dev/null 2>&1 || true
        fi
        ;;
esac

exit 0
