<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>5.0</Version>
		<AssemblyName>DnsRebindingProtectionApp</AssemblyName>
		<RootNamespace>DnsRebindingProtection</RootNamespace>
		<Description>Schützt vor DNS-Rebinding-Angriffen anhand der konfigurierten privaten Domains und Netze.\n\nWarnung: Die App entfernt private IP-Adressen aus den Antworten für alle Domains, die nicht lokal verwaltet werden.</Description>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\ZenitiumDns.ApplicationCommon\ZenitiumDns.ApplicationCommon.csproj">
			<Private>false</Private>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\ZenitiumLibrary\ZenitiumLibrary.csproj">
			<Private>false</Private>
		</ProjectReference>
		<ProjectReference Include="..\..\src\ZenitiumLibrary.Net\ZenitiumLibrary.Net.csproj">
			<Private>false</Private>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<None Update="dnsApp.config">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="README.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
