<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>2.1</Version>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="QRCoder" Version="1.8.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ZenitiumLibrary\ZenitiumLibrary.csproj" />
	</ItemGroup>

</Project>
