<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<Version>4.2</Version>
		<AssemblyName>QueryLogsMySqlApp</AssemblyName>
		<RootNamespace>QueryLogsMySql</RootNamespace>
		<Description>Schreibt alle eingehenden DNS-Anfragen und ihre Antworten in eine MySQL- oder MariaDB-Datenbank, die sich unter Protokolle in der Weboberfläche durchsuchen lässt.\n\nHinweis: Lege vorher einen Datenbankbenutzer mit allen Rechten auf die Datenbank an, zum Beispiel an der MySQL-Konsole als root mit dem gewünschten Datenbank- und Benutzernamen:\nCREATE USER 'user'@'%' IDENTIFIED BY 'password';\nGRANT ALL PRIVILEGES ON DatabaseName.* TO 'user'@'%';\n\nTrage danach in der Konfiguration der App Datenbankname und Verbindungszeichenfolge ein und schalte die Protokollierung ein. Beim Speichern legt die App das Datenbankschema selbst an und beginnt mit der Protokollierung.</Description>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<OutputType>Library</OutputType>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MySqlConnector" Version="2.6.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\ZenitiumDns.ApplicationCommon\ZenitiumDns.ApplicationCommon.csproj">
			<Private>false</Private>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\ZenitiumLibrary.Net\ZenitiumLibrary.Net.csproj">
			<Private>false</Private>
		</ProjectReference>
		<ProjectReference Include="..\..\src\ZenitiumLibrary\ZenitiumLibrary.csproj">
			<Private>false</Private>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<None Update="dnsApp.config">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="README.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
