<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>5.2</Version>
		<AssemblyName>AdvancedForwardingApp</AssemblyName>
		<RootNamespace>AdvancedForwarding</RootNamespace>
		<Description>Leitet Anfragen für viele Domains gebündelt an eigene Forwarder weiter (bedingte Weiterleitung). Für Client-IP-Adressen oder Subnetze lassen sich Gruppen mit jeweils eigener Weiterleitung anlegen. Upstream-Dateien im AdGuard-Format werden unterstützt.\n\nHinweis: Die App arbeitet unabhängig von den eingebauten Weiterleitungszonen des Servers.</Description>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<OutputType>Library</OutputType>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\ZenitiumDns.ApplicationCommon\ZenitiumDns.ApplicationCommon.csproj">
			<Private>false</Private>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\ZenitiumLibrary\ZenitiumLibrary.csproj">
			<Private>false</Private>
		</ProjectReference>
		<ProjectReference Include="..\..\src\ZenitiumLibrary.Net\ZenitiumLibrary.Net.csproj">
			<Private>false</Private>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<None Update="adguard-upstreams.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="dnsApp.config">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="README.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
