<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<Version>1.3</Version>
		<AssemblyName>QueryLogsPostgreSqlApp</AssemblyName>
		<RootNamespace>QueryLogsPostgreSql</RootNamespace>
		<Description>Schreibt alle eingehenden DNS-Anfragen und ihre Antworten in eine PostgreSQL-Datenbank, die sich unter Protokolle in der Weboberfläche durchsuchen lässt.\n\nHinweis: Lege vorher einen Benutzer und eine Datenbank an und gib dem Benutzer alle Rechte darauf, zum Beispiel an der PostgreSQL-Konsole als Administrator mit dem gewünschten Datenbank- und Benutzernamen:\nCREATE USER "user" password 'password';\nCREATE DATABASE "DatabaseName" OWNER "user";\nGRANT ALL PRIVILEGES ON DATABASE "DatabaseName" TO "user";\n\nTrage danach in der Konfiguration der App Datenbankname und Verbindungszeichenfolge ein und schalte die Protokollierung ein. Beim Speichern legt die App die Tabelle selbst an und beginnt mit der Protokollierung.</Description>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<OutputType>Library</OutputType>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Npgsql" Version="10.0.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\ZenitiumDns.ApplicationCommon\ZenitiumDns.ApplicationCommon.csproj">
			<Private>false</Private>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\ZenitiumLibrary.Net\ZenitiumLibrary.Net.csproj">
			<Private>false</Private>
		</ProjectReference>
		<ProjectReference Include="..\..\src\ZenitiumLibrary\ZenitiumLibrary.csproj">
			<Private>false</Private>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<None Update="dnsApp.config">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="README.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
